core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
]

posts/urls.py
from django.urls import path

from .import views 

app_name = 'posts'

urlpatterns = [
    path('post/<int:id>', views.view_post, name='view_post'),
    path('like/<int:id>', views.like_post, name='like_post'),
]

posts/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    post_author = models.ForeignKey(User, on_delete=models.CASCADE)  # loads the USER linked to the profile from django AUTH
    post_content = models.TextField(null=True, blank=True)
    likes = models.ManyToManyField(User, blank=True, related_name="collected_votes")

posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render

from .models import Post

def view_post(request, id):
    post = Post.objects.get(id=id)
    
    context = {'post':post}
    return render(request, 'posts/post_detail.html', context)


def like_post(request, id):
    if request.method == "POST":
        instance = Post.objects.get(id=id)
        if not instance.likes.filter(id=request.user.id).exists():
            instance.likes.add(request.user)
            instance.save() 
            return render( request, 'posts/partials/likes_area.html', context={'post':instance})
        else:
            instance.likes.remove(request.user)
            instance.save() 
            return render( request, 'posts/partials/likes_area.html', context={'post':instance})

posts/templates/posts/partials/likes_area.html
<div class="list-group list-group-horizontal btn-group" id="likesarea" role="group">
    <p>{{ post.likes.count }} likes
    
        <button hx-post="{% url 'posts:like_post' post.id %}" id="like-button" 
          hx-target="#likesarea" hx-swap="outerHTML">
          {% if request.user in post.likes.all %}
            <i class="material-icons" style="font-size:16px;color:green;">check_box</i>
          {% else %}
          <i class="material-icons" style="font-size:16px;color:yellowgreen;">check_box_outline_blank</i>
          {% endif %}
        </button>

    </p> 
    
</div>

posts/templates/posts/post_detail.html
<html>
    <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    </head>
    <body>
        <h1>Post detail page</h1>
        <br>
        <p>{{post.post_author}}</p>
        
        <p>{{post.post_content}}</p>
        <div>
            {% include "posts/partials/likes_area.html" %}
        </div>
    </body>
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (e) => {
          e.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
          })
      </script>
</html>